@echo off
REM Generated by vm.sh smoke -- do not edit.
cd /d C:\iwd2-re
python scripts\auto_start_game.py --slot 3 --ui-script C:\iwd2-re\tmp_ui_script.txt --ui-result C:\iwd2-re\tmp_ui_result.jsonl --ui-go C:\iwd2-re\tmp_ui_go.txt > C:\iwd2-re\vm_s1_out.txt 2>&1
